version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:928052840712:task-definition/spacy-clone:1"
        LoadBalancerInfo:
          ContainerName: "spacy-clone"
          ContainerPort: 80
# Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-0fb5397cc078cc744","subnet-0a7c6903f3e095ad6","subnet-0956f8d48351ff212"]
            SecurityGroups: ["sg-0b5b03577526e7630"]
            AssignPublicIp: "ENABLED"
        CapacityProviderStrategy:
          - Base: 1
            CapacityProvider: "FARGATE_SPOT"
            Weight: 2
          - Base: 0
            CapacityProvider: "FARGATE"
            Weight: 1
