version: 0.0

Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:928052840712:task-definition/spacy-clone:5"
        LoadBalancerInfo:
          ContainerName: "spacy-clone"
          ContainerPort: 80
